---
title: "HW6 by Ximeng"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(p8105.datasets)
library(mgcv)
```

# Problem 2
```{r}
bwt_df = read_csv("data/birthweight.csv") %>%
  drop_na() %>%
  select(bwt, bhead, blength, delwt, gaweeks, babysex)

my_model = lm(bwt ~ bhead + blength + delwt, data = bwt_df) 

bwt_df %>%                            #residual vs fitted plot
  modelr::add_predictions(my_model) %>%
  modelr::add_residuals(my_model) %>%
  ggplot(aes(x = pred, y = resid)) + geom_point(alpha = 0.3) + geom_smooth()

lm_1 = lm(bwt ~ blength + gaweeks, data = bwt_df)

lm_2 = lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = bwt_df)
```

Cross validation
```{r}
cv_df = 
  crossv_mc(bwt_df,100)

cv_df =
  cv_df %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

cv_df = 
  cv_df %>%
  mutate(
    my_model = map(train, ~lm(bwt ~ bhead + blength + delwt, data = .x)),
    lm_1 = map(train, ~lm(bwt ~  blength + gaweeks, data = .x)),
    lm_2 = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = .x))
  ) %>%
  mutate(
    rmse_mymodel = map2_dbl(my_model, test, ~rmse(model = .x, data = .y)),
    rmse_lm1 = map2_dbl(lm_1, test, ~rmse(model = .x, data = .y)),
    rmse_lm2 = map2_dbl(lm_2, test, ~rmse(model = .x, data = .y)))

cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

# Problem 3

Import data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Bootstrap
```{r}
lm(tmax ~ tmin, data = weather_df) %>% #the linear model of interest
  broom::tidy() %>% 
  knitr::kable(digits = 3)  

boot_sample = function(df) {           #create function that can generate bootstrap sample with input of a dataframe
  sample_frac(df, replace = TRUE)
}

boot_strap =                           # create a data frame of the 5000 boot sample with id number
  data_frame(
    strap_number = 1:5000,
    strap_sample = rerun(5000, boot_sample(weather_df))
  )

bootstrap_result =                  #create a data from that map the 5000 sample with its linear model
  boot_strap %>%
  mutate(
    models = map(strap_sample, ~lm(tmax ~ tmin, data = .x)))
```

Get log(beta_0*beta_1)
```{r}
# create a function that can generate the value of log(beta_0*beta_1) with the input of a dataframe
log_beta = function(df){         
  
fit = lm(tmax ~ tmin, data = df)    # firstly generate a linear model with the input datafram

est =                       # secondly create a data frame with the broomed result of linear model
fit %>%
broom::tidy() %>% 
select(term, estimate) %>%        # select parameter of interest
mutate(term = str_replace(term,"\\(Intercept\\)","Intercept")) %>%   # omit the "()"
pivot_wider(                     #pivot wider so the beta_0 and beta_1 can be separated
names_from = "term",
values_from = "estimate"
)

est = 
tibble(        # the output is est dataframe with log(beta_0*beta_1) in it
est,
log = log(pull(est, Intercept) * pull(est, tmin)))

est
}

#rerun the function for 5000 times, each time the dataframe input is a bootstrap sample generate from the weather_df
logbeta_df = rerun(5000, log_beta(boot_sample(weather_df))) %>% 
  bind_rows()

#summarize the mean and CI for log(beta_0*beta_1)
logbeta_df %>%
  summarize(mean = mean(log),
            lower = quantile(log, c(0.025)),
            upper = quantile(log, c(0.975)))

#plot log(beta0*beta1)
logbeta_df %>%
  ggplot(aes(x = log)) + geom_density() + labs(title = "Distributiion of Log(beta_0*beta_1)", x = "log(beta_0*beta_1)", y = "density")
```
The distribution of `log(beta_o*beta_1)` follows a normal distribution, with mean around 2.01.  The 95% CI for `log(beta_o*beta_1)` is (1.96, 2.06)

# get R-squared
```{r}
r_squared = bootstrap_result %>%  #using the dataframe with 5000 linear model generated from bootstrap sample
  mutate(
    result2 = map(models, broom::glance)   # to get r-squared
  ) %>%
  select(-strap_sample, -models) %>%    #select parameter of interest
  unnest(result2) %>%
  janitor::clean_names()

# plot R squared
r_squared %>%
  ggplot(aes(x = r_squared)) + geom_histogram() + labs(title = "Distribution of R-squared", x = "R-squared")

# get mean and CI of R-squared
r_squared %>%
  summarize(mean = mean(r_squared),
            lower = quantile(r_squared, c(0.025)),
            upper = quantile(r_squared, c(0.975)))
```
`R-squared` also follows a normal distribution with mean around 0.911.  The 95% CI is (0.894, 0.927)